services:
  web:
    image: ragobs:latest
    restart: always
    container_name: ragobs-web
    ports:
      - 80:5000
    expose:
      - 5000
    environment:
      - OBSIDIAN_PATH=/obsidian
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./backend/obsidian:/obsidian

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
#    volumes:
#      - qdrant-data:/qdrant/storage

#volumes:
#  qdrant-data: