services:
  web:
    image: daniilsolo/ragobs:latest
    container_name: ragobs-web
    restart: always
    ports:
      - 80:5000
    expose:
      - 5000
    environment:
      - OBSIDIAN_PATH=/obsidian
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=ragobs
    volumes:
      - ./backend/obsidian:/obsidian

  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragobs
    ports:
      - "5432:5432"
    volumes:
      - ragobs_pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  ragobs_pgdata: