FROM python:3.11-alpine AS builder
WORKDIR /app
COPY pyproject.toml ./
RUN python -m pip install --no-cache-dir poetry && poetry config virtualenvs.in-project true && poetry install --no-interaction --no-ansi

FROM python:3.11-alpine as production
WORKDIR /app
COPY --from=builder /app /app
COPY ./src /app/src
CMD ["/app/.venv/bin/uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "5000"]