services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - ragobs_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  ragobs_pgdata: