name: Ruff Linter

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

  push:
    branches:
      - main
    paths:
      - 'backend/**'
      
  workflow_dispatch:
   
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install poetry==1.8.5
          poetry install
      - name: Ruff linter
        working-directory: ./backend
        run: |
          poetry run ruff check src
